# Generated by Django 6.0.7 on 2026-09-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpId', models.IntegerField(primary_key=True, serialize=False)),
                ('EmpName', models.CharField(max_length=40)),
                ('EmpSal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
